MineShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('shop.urls', namespace='shop')),
 )

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]

cart/urls.py
from django.urls import path

from . import views


app_name = 'cart'

urlpatterns = [
    path('add/<int:pk>', views.add_view, name='add'),
    path('remove/<int:pk>', views.remove_view, name='remove'),
    path('', views.cart_view, name='cart'),
]

order/urls.py
from django.urls import path

from . import views


app_name = 'order'

urlpatterns = [
    path('create/', views.order_view, name='create'),
    path('payment/<int:pk>', views.payment_view, name='payment'),
    path('complete/<int:pk>', views.complete_view, name='complete'),
    path('invoice/<int:pk>', views.invoice_view, name='invoice'),
]

shop/urls.py
from django.urls import path

from . import views


app_name = 'shop'

urlpatterns = [
    path('detail/<slug:slug>/<int:pk>', views.detail_view, name="detail"),
    path('category/<slug:slug>/', views.list_view, name='category_list'),
    path('', views.list_view, name='list'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product
from shop.recommender import Recommender

from .cart import Cart


@require_POST
def add_view(request, pk):
    quantity = int(request.POST.get('quantity', default=1))
    override = False if request.POST.get('override') == "False" else True
    product = get_object_or_404(Product, pk=pk)

    cart = Cart(request)
    cart.add(product, quantity, override=override)
    return redirect('cart:cart')


@require_POST
def remove_view(request, pk):
    product = get_object_or_404(Product, pk=pk)

    cart = Cart(request)
    cart.remove(product)
    return redirect('cart:cart')


def cart_view(request):
    cart = Cart(request)
    products = [item['product'] for item in cart]
    if products:
        r = Recommender()
        recommended_products = r.suggest_products_for(products)
    else:
        recommended_products = None
    return render(request, 'cart/cart.html',
                  {'recommended_products': recommended_products})

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load get_image %}
{% load i18n %}

{% block title %}{% translate "Cart" %}{% endblock title %}


{% block content %}
    <div class="container container-content">
        <h2 class="content-title">{% translate "Your shopping cart" %}</h2>

        <table>
            <thead>
                <tr>
                    <th>{% translate "Product" %}</th>
                    <th>{% translate "Quantity" %}</th>
                    <th>{% translate "Remove" %}</th>
                    <th>{% translate "Unit price" %}</th>
                    <th>{% translate "Price" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                    <tr>
                        <td>
                            <div class="container-table">
                                <a href="{{ item.product.get_absolute_url }}">
                                    <h3 class="table-item-title">{{item.product.name}}</h3>
                                    <img src="{% get_image item.product.image %}" alt="" class="table-item-image">
                                </a>
                            </div>
                        </td>
                        <td>
                            <form action="{% url 'cart:add' item.product.pk %}" method="post">
                                {% csrf_token %}
                                <input type="number" value="{{ item.quantity }}" name="quantity" min="1" max="20">
                                <button class="btn">{% trans "update" %}</button>
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'cart:remove' item.product.pk %}" method="post">
                                {% csrf_token %}
                                <button class="btn">{% translate "remove" %}</button>
                            </form>
                        </td>
                        <td>
                            <span class="price">{{ item.price }} {% trans "rub" %}</span>
                        </td>
                        <td>
                            <span class="price">{{ item.total_price }} {% trans "rub" %}</span>
                        </td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="4" class="table-total">{% trans "Total" %}:</td>
                    <td><span class="price">{{ cart.get_total_price }} {% trans "rub" %}</span></td>
                </tr>
            </tbody>
        </table>
        <div class="container-btn">
            <a href="{% url 'shop:list' %}" class="btn">{% trans "continue shopping" %}</a>
            <a href="{% url 'order:create' %}" class="btn">{% trans "checkout" %}</a>
        </div>

        {% if recommended_products %}
            <div class="recommendations"></div>
                <h2 class="sidebar-title">{% translate "You can be interested in" %}</h2>
                <div class="recommendations-body">
                    <ul>
                        {% for product in recommended_products %}
                            <li>
                                <a href="{{ product.get_absolute_url }}">
                                    <div class="sidebar-item">
                                        <h3 class="sidebar-item-title">{{ product.name }}</h3>
                                        <img src="{% get_image product.image %}" alt="" class="sidebar-item-image">
                                    </div>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}