MineShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('shop.urls', namespace='shop')),
 )

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]

cart/urls.py
from django.urls import path

from . import views


app_name = 'cart'

urlpatterns = [
    path('add/<int:pk>', views.add_view, name='add'),
    path('remove/<int:pk>', views.remove_view, name='remove'),
    path('', views.cart_view, name='cart'),
]

shop/urls.py
from django.urls import path

from . import views


app_name = 'shop'

urlpatterns = [
    path('detail/<slug:slug>/<int:pk>', views.detail_view, name="detail"),
    path('category/<slug:slug>/', views.list_view, name='category_list'),
    path('', views.list_view, name='list'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=50,
                            db_index=True)
    slug = models.SlugField(max_length=50,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def get_absolute_url(self):
        return reverse('shop:category_list',
                       kwargs={'slug': self.slug})

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name="products",
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    image = models.ImageField(upload_to='uploads/%Y/%m/%d/',
                              blank=True,
                              null=True)
    description = models.TextField()
    brief = models.CharField(max_length=200,
                             blank=True,
                             null=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)

    class Meta:
        ordering = ('name',)
        index_together = ('id', 'slug')

    def get_absolute_url(self):
        return reverse('shop:detail',
                       kwargs={'pk': self.pk,
                               'slug': self.slug})

    def __str__(self):
        return self.name

shop/views.py
import redis

from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.conf import settings

from .models import Category, Product
from .recommender import Recommender
from .utils import is_ajax


# r = redis.Redis(host=settings.REDIS_HOST,
#                 port=settings.REDIS_PORT,
#                 db=settings.REDIS_DB)

r = redis.from_url(settings.REDIS_URL)


def list_view(request, slug=None):
    categories = Category.objects.all()
    products = Product.objects.all()
    active_category = None
    if slug:
        category = get_object_or_404(Category, slug=slug)
        products = category.products.all()
        active_category = category.name
    # Popular products
    product_ranking = r.zrange('product_ranking', 0, 4, desc=True)
    product_pks = [int(pk) for pk in product_ranking]
    popular_products = list(Product.objects.filter(pk__in=product_pks))
    popular_products.sort(key=lambda x: product_pks.index(x.pk))

    # Pagination
    paginator = Paginator(products, 5)
    page_number = int(request.GET.get('page', 1))
    if page_number > paginator.num_pages:
        return HttpResponse('')
    products = paginator.get_page(page_number)
    if is_ajax(request):
        return render(request, 'shop/products_ajax.html', {'products': products})
    return render(request, 'shop/list.html',
                  {'categories': categories,
                   'products': products,
                   'active_category': active_category,
                   'popular_products': popular_products})


def detail_view(request, slug, pk):
    product = get_object_or_404(Product, pk=pk, slug=slug)

    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)

    return render(request, 'shop/detail.html',
                  {'product': product,
                   'recommended_products': recommended_products})

shop/templates/base.html
{% load static %}
{% load i18n %}
{% load language_url %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <header>
        <div class="container container-between">
            <a href="{% url 'shop:list' %}">
                <img src="{% static 'img/logo.png' %}" alt="" class="img-header">
            </a>

            <span class="cart">
            <a href="{% url 'cart:cart' %}" class="cart">
                {% with cart|length as total_items %}
                    {% if total_items %}
                        <p>
                        {% blocktranslate with total_price=cart.get_total_price count total_items=total_items %}
                        {{total_items}} item, <span class="price">{{ total_price }} rub</span>
                        {% plural %}
                        {{total_items}} items, <span class="price">{{ total_price }} rub</span>
                        {% endblocktranslate %}
                        </p>
                    {% else %}
                        <p>{% translate "Empty" %}</p>
                    {% endif %}
                {% endwith %}
                <img src="{% static 'img/cart.png' %}" alt="" class="img-header">
            </a>

            {% get_current_language as LANGUAGE_CODE %}
            <span class="language-select"><a href="{{ request.path|language_url:"ru" }}" {% if LANGUAGE_CODE == 'ru' %}class="active-category"{% endif %}>ru</a> / <a href="{{ request.path|language_url:"en" }}" {% if LANGUAGE_CODE == 'en' %}class="active-category"{% endif %}>en</a></span>
            </span>
        </div>
    </header>

    {% block content %}
    {% endblock content %}
    
    <footer>
        <p>{% translate "Mady by Ilshat G." %}</p>
    </footer>

    {% block scripts %}
    {% endblock scripts %}
</body>
</html>