MineShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('shop.urls', namespace='shop')),
 )

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]

cart/urls.py
from django.urls import path

from . import views


app_name = 'cart'

urlpatterns = [
    path('add/<int:pk>', views.add_view, name='add'),
    path('remove/<int:pk>', views.remove_view, name='remove'),
    path('', views.cart_view, name='cart'),
]

order/urls.py
from django.urls import path

from . import views


app_name = 'order'

urlpatterns = [
    path('create/', views.order_view, name='create'),
    path('payment/<int:pk>', views.payment_view, name='payment'),
    path('complete/<int:pk>', views.complete_view, name='complete'),
    path('invoice/<int:pk>', views.invoice_view, name='invoice'),
]

order/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from shop.models import Product


class Order(models.Model):
    first_name = models.CharField(verbose_name=_('First Name'),max_length=100)
    last_name = models.CharField(verbose_name=_('Last Name'), max_length=100)
    email = models.EmailField(verbose_name=_('Email'))
    city = models.CharField(verbose_name=_('City'), max_length=200)
    address = models.CharField(verbose_name=_('Address') ,max_length=200)
    postal_code = models.CharField(verbose_name=_('Postal Code'), max_length=20)
    paid = models.BooleanField(default=False)
    payment_time = models.DateTimeField(blank=True,
                                        null=True)

    def __str__(self):
        return f'Order #{self.pk}'

    def get_total_price(self):
        return sum(item.get_cost() for item in self.order_items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='order_items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    quantity = models.IntegerField()

    def get_cost(self):
        return self.price * self.quantity

    def __str__(self):
        return f'{self.quantity}x {self.product.name} for Order #{self.order.pk}'

order/forms.py
from localflavor.ru.forms import RUPostalCodeField

from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Order


class OrderForm(forms.ModelForm):
    postal_code = RUPostalCodeField(label=_('Postal Code'))
    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email',
                  'city', 'address', 'postal_code')

order/views.py
import redis

from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required
from django.utils import timezone

from cart.cart import Cart
from shop.recommender import Recommender

from .forms import OrderForm
from .models import OrderItem, Order
from .tasks import send_order_created_email, send_order_paid_email
from .utils import write_invoice_pdf


# r = redis.Redis(host=settings.REDIS_HOST,
#                 port=settings.REDIS_PORT,
#                 db=settings.REDIS_DB)
r = redis.from_url(settings.REDIS_URL)


def payment_view(request, pk):
    order = get_object_or_404(Order, pk=pk)
    return render(request, 'order/payment.html', {'order': order})


def complete_view(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.paid = True
    order.payment_time = timezone.now()
    order.save()
    send_order_paid_email(pk)
    return redirect('shop:list')


def order_view(request):
    if request.method == 'POST':
        order_form = OrderForm(request.POST)
        if order_form.is_valid():
            cart = Cart(request)
            order = order_form.save()
            for item in cart:
                # Create new order item
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity']
                )
                # Update ranking for products
                r.zincrby('product_ranking', item['quantity'], item['product'].pk)
            rec = Recommender()
            rec.products_bought(order)
            cart.clear()
            payment_url = request.build_absolute_uri(reverse('order:payment', args=[order.pk,]))
            send_order_created_email.delay(order.pk, order.email, payment_url)
            return redirect('order:payment', pk=order.pk)
    else:
        order_form = OrderForm()

    return render(request, 'order/order.html', {'order_form': order_form})


@staff_member_required
def invoice_view(request, pk):
    order = get_object_or_404(Order, pk=pk)
    if not order.paid:
        return "Doesn't paid"
    response = HttpResponse(content_type="application/pdf")
    write_invoice_pdf(response, pk)
    response['Content-Disposition'] = f'attachment; filename="invoice_{pk}.pdf"'
    return response

order/templates/order/invoice.html
<html>
<body>
    <div class="container">
        <h1>MineShop</h1>

        <div class="invoice">
            <p class="invoice-number">Invoice #{{ order.pk }}</p>
            <p class="invoice-date">{{ order.payment_time }}</p>
        </div>

        <h2>Bill to</h2>

        <div class="order-info">
            <p class="name">{{ order.first_name }}</p>   
            <p class="email">{{ order.email }}</p>
            <p class="address">{{ order.address }}</p>
            <p><span class="postal">{{ order.postal_code }}</span>, <span class="city">{{ order.city }}</span></p>
        </div>

        <h2>Items bought</h2>

        <table>
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Cost</th>
                </tr>
            </thead>
            <tbody>
                {% for product in order.order_items.all %}
                    <tr>
                        <td>{{ product.product.name }}</td>
                        <td>{{ product.price }} rub</td>
                        <td>{{ product.quantity }}</td>
                        <td>{{ product.get_cost }} rub</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="3">Total</td>
                    <td>{{ order.get_total_price }} rub</td>
                </tr>
            </tbody>
        </table>

        <span class="paid">Paid</span>
    </div>
</body>
</html>

order/templates/order/order.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Order" %}{% endblock title %}

{% block content %}
    <div class="container container-content container-checkout">
        <div class="checkout">
            <h2 class="checkout-title">{% trans "Checkout" %}</h2>

            <form method="post" class="form-checkout">
                {% csrf_token %}
                {{ order_form.as_p }}
                <br><br>
                <div class="btn-center">
                    <button type="submit" class="btn">{% translate "submit" %}</a>
                </div>
            </form>
        </div>

        <div class="order">
            <h3>{% trans "Your order" %}</h3>
            <ul class="order-list">
                {% for item in cart %}
                <li>{{ item.quantity }}x {{ item.product.name }} <span class="price order-price">{{ item.total_price }} {% trans "rub" %}</span></li>
                {% endfor %}
            </ul>

            <p class="order-total">{% trans "Total" %}: <span class="price">{{ cart.get_total_price }} {% trans "rub" %}</span></p>
        </div>
    </div>
{% endblock content %}

order/templates/order/payment.html
{% extends 'base.html' %}
{% load i18n %}
{% load l10n %}

{% block title %}{% trans "Payment" %}{% endblock title %}

{% block content %}
    <div class="container container-content">
        {% if not order.paid %}
            <h1 class="content-title">{% trans "Payment" %}</h1>
            <div id="paypal-button-container"></div>
        {% else %}
            <h1 class="content-title">
                {% trans "This order has already been paid" %}.
            </h1>
        {% endif %}
    </div>
{% endblock content %}

{% block scripts %}
    {% localize off %}
     <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=AbtCWfMO7w78HBFoHmQqnJwlu38ZdYD3Ahlg9UYQtALDvAPVCfZx99LpogkIi9F-AMHC_qQES20bME2g&currency=RUB"></script>

    <script>
        const order_price = '{{ order.get_total_price }}';
        const url = "{% url 'order:complete' order.pk %}";
        console.log(order_price, url)
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({
            // Set buttons style
            style: {
                color: 'black'
            },

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: order_price
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    //fetch(url, {
                    //    headers: {"X-Requested-With": ////"XMLHttpRequest"}
                    //})
                    window.location.href = url
                });
            },

            // Handle errors
            onError: function (err) {
                console.log(err);
            }


        }).render('#paypal-button-container');
    </script>
    {% endlocalize %}
{% endblock scripts %}